### ISSUE TITLE
capture_all_str treating given string as path for few inputs

### ISSUE THREAD

**Issue by akhikolla** [tdhock/nc#13]
Hello @tdhock,
I am trying to parse a given string to extract the package name and its folder. But capture_all_str treats the given string as a path instead of parsing it.
Also, it is not treating all the strings as paths but only the path that exists in the system.
Is there a way that this given string can be treated as a string instead of a path and give expected results?

![image](https://user-images.githubusercontent.com/31878891/85237483-2e594200-b3dc-11ea-95cd-dff66f8233c1.png)

Thanks

**Comment by tdhock** [comment]
no need to use regex for parsing directory/file names. (that would be un-necessarily complicated)
use dirname(path) and basename(path) instead, is that OK?

**Comment by tdhock** [comment]
btw treating a single input as a file only happens if the file exists, for convenience. the line of code is:
https://github.com/tdhock/nc/blob/master/R/capture_all_str.R#L27
```r
  if(length(subject.vec)==1 && file.exists(subject.vec)){
```
which means that if the length is more than 1, it would work, e.g.
```r
nc::capture_all_str(c("", path), etc)
```

**Comment by akhikolla** [comment]
Yes, @tdhock using basename() and dirname() is easy.
Although length(subject.vec) is 1, here testSAN is a directory and not a file so it is throwing the error.
But the second path which I am using above doesn't even exist then how am I getting the expected results?

**Comment by tdhock** [comment]
basename/dirname/file.path/system.file work even if the directory/file does not exist.
use system.file(file, mustWork=FALSE) if you want the function to stop with an error when the file does not exist.

**Comment by tdhock** [comment]
hi if your issue is resolved can you please close?

**Comment by akhikolla** [comment]
Thanks for the solution @tdhock.
