### ISSUE TITLE
Tests broken by upcoming data.table release

### ISSUE THREAD

**Issue by MichaelChirico** [tdhock/nc#15]
Hi Toby,

`data.table` will be releasing a new version soon and some of your tests are breaking:

```
── 1. Failure: RE2 gender dob example (@test-CRAN-multiple.R#115)  ─────────────
na.children$dob inherits from `IDate/Date` not `character`.

── 2. Failure: ICU gender dob example (@test-CRAN-multiple.R#115)  ─────────────
na.children$dob inherits from `IDate/Date` not `character`.

── 3. Failure: PCRE gender dob example (@test-CRAN-multiple.R#115)  ────────────
na.children$dob inherits from `IDate/Date` not `character`.

── 4. Failure: RE2 gender dob example na.rm=TRUE (@test-CRAN-multiple.R#176)  ──
children$dob inherits from `IDate/Date` not `character`.

── 5. Failure: ICU gender dob example na.rm=TRUE (@test-CRAN-multiple.R#176)  ──
children$dob inherits from `IDate/Date` not `character`.

── 6. Failure: PCRE gender dob example na.rm=TRUE (@test-CRAN-multiple.R#176)  ─
children$dob inherits from `IDate/Date` not `character`.
```

Looking at the tests I think everything is due to the recent enhancement (we think at least!) to detect and read dates with `fread` and import them as `IDate`s (see [here](https://github.com/Rdatatable/data.table/pull/4464)).

I'll file a PR fixing these tests shortly.

**Comment by mattdowle** [comment]
Hi @tdhock,
Hope this change is ok. Would you mind confirming you've seen the PR and are ok for us to proceed to release data.table to CRAN?
Thanks, Matt

**Comment by tdhock** [comment]
cool that you guys got the IDates working! And I see you already released to CRAN. sorry for the late reply, been on vacation, just got back and will probly get time to fix this / merge your PR (thanks!) later this month.
