### ISSUE TITLE
Offer 'type.convert' in interface?

### ISSUE THREAD

**Issue by MichaelChirico** [tdhock/nc#28]
Finally giving {nc} a try, it's quite handy!

It took me a while to find out `capture_first_vec()` offers a way to do type conversion:

> Each function must be un-named, and is used to convert the previous capture `group`.

This is nice, but maybe "too much" flexibility. I think `utils::type.convert()` would offer a much simpler interface here, instead of 4 different `as.integer` entries, I could just pass `type.convert=TRUE` and let R figure out the appropriate type for me. That's also the approach `data.table::tstrsplit()` takes which would make it more familiar as well.

**Comment by tdhock** [comment]
Hey that is a great idea! can you please try #29 and tell me if that is what you had in mind?

**Comment by tdhock** [comment]
for completeness the 4 different as.integer entries were something like this, which is similar to a new example:
```r
nc::capture_first_vec(
  c("p=0,4 v=3,-3","p=6,3 v=-1,-3"),
  "p=",
  px="[0-9]", as.integer,
  ",",
  py="[0-9]", as.integer,
  " v=",
  vx="[-0-9]+", as.integer,
  ",",
  vy="[-0-9]+", as.integer)
```
one way to use the old code (before type.convert arg) would be by defining a sub-pattern list as below:
```r
ipat <- list("[-0-9]+", as.integer)
nc::capture_first_vec(
  c("p=0,4 v=3,-3","p=6,3 v=-1,-3"),
  "p=",
  px=ipat,
  ",",
  py=ipat,
  " v=",
  vx=ipat,
  ",",
  vy=ipat)
```
